export const FeatureDescriptions = {
	'Hybrid': 'Automatically switches between VR and Flat',
    'Mixed Reality': 'Table can be played in VR and placed in your environment',
	'VR': 'Table can be played with a VR headset',
	'FSS': 'Table works well on a single screen in ladscape orientation',
	'4k': 'Table has high resolution textures',
	'MOD': 'Table is a modification of another table',
    'Retheme': 'Table uses a different table with a new theme applied',
    'VPU Patch': 'Uses VPURemix to patch an original table file',
	'FastFlips': 'Simulates quicker solenoid ramp up on flippers',
	'SSF': 'Has audio content for surround sound (positional audio)',
	// 'P-ROC': '',
	'FlexDMD': 'An external DMD renderer',
	'Music': 'Table includes music files',
	'incl. B2S': 'Table includes backglass files',
	'incl. ROM': 'Table includes ROM files',
    'incl. nvram': 'Table includes nvram (settings and scores) file',
	'incl. Art': 'Table includes additional artwork',
	'incl. PuP': 'Table includes a PuP pack',
	'incl. Video': 'Table includes video files',
	'no ROM': 'Table does not require ROM emulation',
	'Kids': 'Table is geared towards children',
	'Adult': 'Table has adult themes',
	'nFozzy': 'Table has improved/realistic physics',
	'Fleep': 'Table has improve ball sounds',
	'LUT': 'Table coloring can be changed',
	'Scorbit': 'Table integrates with Scorbit score management',
	'BAM': 'Future Pinball table requires BAM (better arcade mode)',
	'FizX': 'Future Pinball table with improved physics',
    'DOF': 'Table integrates with DOF (solenoids and lights)',
};